List animals = [
  'Avengers.gif',
  'bahubali.gif',
  'camel.gif',
  'captain america.gif',
  'cats.gif',
  'dogs.gif',
  'fishes.jpeg',
  'fox.webp',
  'gadar.gif',
  'happy new year.gif',
  'hera pheri.gif',
  'horse.gif',
  'kangaroos.gif',
  'koi mil gaya.gif',
  'mouse.gif',
  'padmavat.gif',
  'rabbits.gif',
  'The hulk.gif',
  'war.gif',
  'zebras.jpeg'
];

List spot =[
  'sidiff2.gif',
  'stdiff1.gif',
  'stdiff3.jpeg',
  'stdiff5.jpg',
  'stdiff6.jpg',
  'stdiff7.jpg',
  'stdiff8.webp',
  'stdiff10.jpg',
  'stdiff4.gif',
  'stdiff9.jpg',
];
